package session

// SessionVarOperatorAuthStatus ...
const SessionVarOperatorAuthStatus = "auth_status"

// SessionValOperatorAuthStatus0 ...
const SessionValOperatorAuthStatus0 = "0"

// SessionValOperatorAuthStatus1 ...
const SessionValOperatorAuthStatus1 = "1"

// SessionValOperatorAuthStatus2 ...
const SessionValOperatorAuthStatus2 = "2"

// SessionValOperatorAuthStatus3 ...
const SessionValOperatorAuthStatus3 = "3"

// SessionVarOperatorAuthID ...
const SessionVarOperatorAuthID = "Id"

// SessionVarOperatorID ...
const SessionVarOperatorID = "operator_id"

// SessionValAccountStatus ...
const SessionValAccountStatus = "user_status"

// SessionValFirstLoginFlg ...
const SessionValFirstLoginFlg = "first_login"

// SessionValOperatorFirstName ...
const SessionValOperatorFirstName = "first_name"

// SessionValOperatorFamilyName ...
const SessionValOperatorFamilyName = "family_name"

// SessionValOperatorRole ...
const SessionValOperatorRole = "role"

// SessionValOperatorRoleDetail ...
const SessionValOperatorRoleDetail = "role_detail"

// SessionValOperatorPhoneNumber ...
const SessionValOperatorPhoneNumber = "phone_number"

// SessionVarMysqlstoreExpiresOn ...
const SessionVarMysqlstoreExpiresOn = "expires_on"

// SessionValExpired ...
const SessionValExpired = "expired"

// SessionValKey ...
const SessionValKey = "key"
